/* Fictional company, fictional people, fictional deadlines. */
const DATA = {
  /* company, me, people and rooms are filled in by js/config.js — they follow
     whatever workspace the user set up on the boot screen. */
  company: '', me: null, people: [], rooms: [],

  /* ---------------- Linear ---------------- */
  teams: ['ENG', 'PLAT', 'GRW', 'DES'],
  issueTitles: [
    'Sessions dropped from the ingest queue under backpressure',
    'Cohort filter resets when you switch workspaces',
    'Add retry budget to the webhook dispatcher',
    'Trim 400ms off first paint on the dashboard route',
    'Funnel step ordering is unstable for tied timestamps',
    'Migrate feature flags off the legacy KV store',
    'Timezone drift in the weekly digest email',
    'Rate limit the export endpoint per org, not per key',
    'Backfill missing person properties for Q3',
    'Flaky test: replay_ingest_spec keeps timing out in CI',
    'Empty state for teams with zero events looks broken',
    'SSO logout leaves a stale session cookie',
    'Batch the property-definition writes',
    'Sampling banner shows even when sampling is off',
    'Dark mode contrast fails on the chart legend',
    'Split the ingest worker into two consumer groups',
    'Cache the org settings lookup on the hot path',
    'Autocomplete drops results past 50 properties',
    'Webhook signatures rotate without a grace window',
    'Dashboard tiles reflow twice on first render',
    'Person merge loses the earliest first_seen',
    'Query builder forgets the date range on back-navigation',
    'Ingest lag metric lies while sampling is on',
    'Slow query log has no org id, so nothing is actionable',
    'Retention chart off by one week at month boundaries',
    'Bulk delete has no confirmation and no undo',
    'Search returns archived projects to non-admins',
    'CSV export truncates at 10k rows without warning',
    'Consumer group rebalance drops in-flight batches',
    'Audit log misses role changes made by the API',
    'Onboarding checklist never marks step 3 complete',
    'Feature flag evaluation adds 40ms to cold starts',
    'Session replay scrubber jumps on long recordings',
    'Alert emails send twice when two rules match',
    'Free plan banner covers the toolbar on small screens',
  ],
  labels: [
    ['bug', '#e5484d'], ['perf', '#e2b33c'], ['infra', '#00b4d8'],
    ['design', '#9b5de5'], ['chore', '#6b7280'], ['growth', '#2bb673'],
    ['a11y', '#ff7ab6'], ['security', '#f4845f'], ['dx', '#4cc9f0'],
  ],
  statuses: [
    ['Backlog', '#6b7280'], ['Todo', '#9aa4b2'], ['In Progress', '#e2b33c'],
    ['In Review', '#9b5de5'], ['Done', '#2bb673'],
  ],
  linearActivity: [
    'moved {i} to In Review', 'commented on {i}', 'assigned {i} to {p}',
    'added label perf to {i}', 'linked a PR to {i}', 'changed priority of {i} to High',
    'moved {i} to Done', 'created {i}', 'added {i} to Cycle 24',
    'estimated {i} at 3 points', 'unblocked {i}', 'reopened {i}',
    'marked {i} as a duplicate', 'subscribed to {i}', 'moved {i} to In Progress',
    'attached a Figma file to {i}', 'left a review on {i}', 'snoozed {i} until Monday',
  ],

  /* ---------------- code ---------------- */
  files: [
    { path: 'src/ingest/queue.ts', lang: 'ts' },
    { path: 'src/ingest/backpressure.ts', lang: 'ts' },
    { path: 'src/api/webhooks.ts', lang: 'ts' },
    { path: 'src/lib/retry.ts', lang: 'ts' },
    { path: 'src/lib/cache.ts', lang: 'ts' },
    { path: 'src/ui/Funnel.tsx', lang: 'tsx' },
    { path: 'src/ui/CohortFilter.tsx', lang: 'tsx' },
    { path: 'src/ui/EmptyState.tsx', lang: 'tsx' },
    { path: 'tests/queue.spec.ts', lang: 'ts' },
    { path: 'tests/retry.spec.ts', lang: 'ts' },
  ],
  snippets: [
    [
      'export async function drain(q: Queue, budget: RetryBudget) {',
      '  const batch = await q.take(BATCH_SIZE);',
      '  if (!batch.length) return { drained: 0, requeued: 0 };',
      '',
      '  const results = await Promise.allSettled(',
      '    batch.map((ev) => sink.write(ev)),',
      '  );',
      '',
      '  let requeued = 0;',
      '  for (const [i, r] of results.entries()) {',
      '    if (r.status === "rejected" && budget.take()) {',
      '      await q.requeue(batch[i], backoff(batch[i].attempts));',
      '      requeued++;',
      '    }',
      '  }',
      '  return { drained: batch.length - requeued, requeued };',
      '}',
    ],
    [
      'const backoff = (attempt: number) =>',
      '  Math.min(MAX_DELAY_MS, BASE_MS * 2 ** attempt) * jitter();',
      '',
      '// Full jitter. Without it every worker retries on the same tick',
      '// and we stampede the sink we were trying to protect.',
      'function jitter() {',
      '  return 0.5 + Math.random() * 0.5;',
      '}',
      '',
      'export class RetryBudget {',
      '  private tokens: number;',
      '  constructor(private ratio = 0.2, private floor = 10) {',
      '    this.tokens = floor;',
      '  }',
      '  take(): boolean {',
      '    if (this.tokens <= 0) return false;',
      '    this.tokens -= 1;',
      '    return true;',
      '  }',
      '}',
    ],
    [
      'export function orderSteps(steps: Step[]): Step[] {',
      '  // Ties on timestamp resolved in insertion order, which is whatever',
      '  // the query planner felt like that day. Break on id instead.',
      '  return [...steps].sort((a, b) =>',
      '    a.ts === b.ts ? a.id.localeCompare(b.id) : a.ts - b.ts,',
      '  );',
      '}',
      '',
      'export function conversion(steps: Step[]): number[] {',
      '  const ordered = orderSteps(steps);',
      '  const first = ordered[0]?.count ?? 0;',
      '  if (!first) return ordered.map(() => 0);',
      '  return ordered.map((s) => s.count / first);',
      '}',
    ],
    [
      'type Entry<T> = { value: T; expires: number };',
      '',
      'export function readThrough<T>(ttlMs: number, load: (k: string) => Promise<T>) {',
      '  const store = new Map<string, Entry<T>>();',
      '  const inflight = new Map<string, Promise<T>>();',
      '',
      '  return async function get(key: string): Promise<T> {',
      '    const hit = store.get(key);',
      '    if (hit && hit.expires > Date.now()) return hit.value;',
      '',
      '    // Collapse concurrent misses so one cold key is one load, not fifty.',
      '    const pending = inflight.get(key);',
      '    if (pending) return pending;',
      '',
      '    const p = load(key).finally(() => inflight.delete(key));',
      '    inflight.set(key, p);',
      '    const value = await p;',
      '    store.set(key, { value, expires: Date.now() + ttlMs });',
      '    return value;',
      '  };',
      '}',
    ],
    [
      'export function verify(req: Request, secrets: string[]): boolean {',
      '  const sig = req.headers.get("x-halcyon-signature");',
      '  if (!sig) return false;',
      '',
      '  // Accept the previous secret for one rotation window, otherwise',
      '  // every rotation is an outage for whoever deploys second.',
      '  return secrets.some((s) => timingSafeEqual(sign(req.body, s), sig));',
      '}',
    ],
    [
      'export function EmptyState({ onCreate }: Props) {',
      '  return (',
      '    <div className="empty">',
      '      <h3>No events yet</h3>',
      '      <p>Send your first event and this fills in within a minute.</p>',
      '      <Button onClick={onCreate}>Install the SDK</Button>',
      '    </div>',
      '  );',
      '}',
    ],
    [
      'describe("drain", () => {',
      '  it("stops requeueing once the budget is spent", async () => {',
      '    const q = fakeQueue(20);',
      '    const budget = new RetryBudget(0.2, 3);',
      '    sink.write.mockRejectedValue(new Error("slow"));',
      '',
      '    const { requeued } = await drain(q, budget);',
      '',
      '    expect(requeued).toBe(3);',
      '    expect(q.dead).toHaveLength(17);',
      '  });',
      '});',
    ],
  ],
  terminalCmds: [
    ['pnpm test -- queue', [
      '  ✓ drains a full batch (28 ms)',
      '  ✓ requeues rejected writes within budget (41 ms)',
      '  ✓ stops requeueing when the budget is spent (12 ms)',
      '  ✓ applies full jitter to the backoff (9 ms)',
      '',
      ' Test Files  1 passed (1)',
      '      Tests  4 passed (4)',
      '   Duration  1.24s',
    ]],
    ['git status --short', [
      ' M src/ingest/queue.ts',
      ' M src/lib/retry.ts',
      '?? tests/backpressure.spec.ts',
    ]],
    ['pnpm typecheck', ['tsc --noEmit -p tsconfig.json', '', 'Done in 6.8s.']],
    ['git log --oneline -5', [
      '4f2a1c9 fix(ingest): honor retry budget on requeue',
      'b81e30d perf(ui): memoize funnel step ordering',
      '9cc4471 chore: bump vitest to 2.1.4',
      '2ad0f18 fix(auth): clear session cookie on SSO logout',
      'e70b665 feat(flags): read-through cache for org settings',
    ]],
    ['pnpm build', [
      'vite v5.4.8 building for production...',
      '✓ 1284 modules transformed.',
      'dist/assets/index-8a1f0c2.js   412.06 kB │ gzip: 128.44 kB',
      '✓ built in 9.31s',
    ]],
    ['git diff --stat', [
      ' src/ingest/queue.ts  | 24 +++++++++++++++---------',
      ' src/lib/retry.ts     | 31 +++++++++++++++++++++++++++++--',
      ' 2 files changed, 46 insertions(+), 9 deletions(-)',
    ]],
    ['pnpm lint --fix', [
      '',
      'Checked 218 files in 1.9s. No fixes applied.',
      'Found 0 errors, 2 warnings.',
    ]],
    ['docker compose ps', [
      'NAME                STATUS              PORTS',
      'halcyon-postgres    Up 4 hours          5432/tcp',
      'halcyon-redis       Up 4 hours          6379/tcp',
      'halcyon-clickhouse  Up 4 hours (healthy) 8123/tcp',
    ]],
    ['gh pr checks 2841', [
      'All checks were successful',
      '0 cancelled, 0 failing, 4 successful, 0 skipped',
      '',
      'build      pass  2m41s',
      'typecheck  pass  1m08s',
      'unit       pass  3m22s',
      'e2e        pass  6m54s',
    ]],
    ['kubectl get pods -l app=ingest', [
      'NAME                      READY   STATUS    RESTARTS   AGE',
      'ingest-7c9f4b8d6-2xk4p    1/1     Running   0          6h',
      'ingest-7c9f4b8d6-9mvqz    1/1     Running   0          6h',
      'ingest-7c9f4b8d6-lr7ts    1/1     Running   1          6h',
    ]],
  ],

  /* ---------------- Roam (virtual office) ---------------- */
  sharedRooms: [
    { name: 'Ingest war room', kind: 'meeting' },
    { name: 'Design review', kind: 'meeting' },
    { name: 'Theater', kind: 'theater' },
    { name: 'Kitchen', kind: 'social' },
    { name: 'Focus row', kind: 'focus' },
    { name: 'Whiteboard', kind: 'meeting' },
    { name: 'Lounge', kind: 'social' },
    { name: 'Backstage', kind: 'focus' },
  ],
  /* Group channels are fixed; the DMs below them follow the current team. */
  groupThreads: [
    { name: 'ingest-rewrite', kind: 'group' },
    { name: 'design-crit', kind: 'group' },
    { name: 'incidents', kind: 'group' },
  ],
  roamThreads: [],
  roamChat: [
    'shadow read has been clean for 14 hours, no diffs',
    'knocking on your office in five, need two minutes on the rebalance plan',
    'the lag graph is finally boring, which is the goal',
    'anyone else seeing the digest land an hour early in Lisbon?',
    'pushed the jitter fix, CI is green',
    'I put the migration note in the doc, second pair of eyes welcome',
    'grabbing coffee, back in ten',
    'can we do the crit in the Theater instead? more room',
    'the empty state is doing too much work, cutting it to one sentence',
    'on-call handoff done, nothing open',
    'p99 is 840ms, down from 2.1s last week',
    'that flaky test is the queue timing out, not the assertion',
    'I will take the rebalance story if nobody has started it',
    'customer call moved to 3, so the 1:1 slides too',
    'screensharing now if you want to see the trace',
    'nice, the retry budget caught it before the sink did',
    'do we still need the sampling banner? it lies during incidents',
    'joining from my phone, audio only',
    'the export limit per org shipped, timeouts are basically gone',
    'who owns the audit log gap? I can pick it up',
    'writing the incident review now, short version: we stampeded ourselves',
    'the funnel tie-break has been broken since the first release, apparently',
    'moving to the war room, easier to talk through the diagram',
    'that PR is ready whenever you have ten minutes',
    'lunch, back at half past',
    'no need to rush it, the freeze is Thursday next week',
    'I can repro the cohort filter reset every time now',
    'good catch, that was my typo in the config',
    'let us not do the rebalance during peak, even if it works',
    'standup in the Theater in two minutes',
  ],
  roamEvents: [
    '{p} moved to {r}', '{p} knocked on {r}', '{p} joined {r}',
    '{p} is screensharing in {r}', '{p} started a drop-in with {q}',
    '{p} went into focus mode', '{p} left {r}', '{p} booked the Theater',
  ],

  /* ---------------- Gmail ---------------- */
  /* [from, subject, body, the reply you type back] */
  emails: [
    ['Mara Velez', 'Re: ingest rewrite — sequencing',
      'Pulled the migration note into the doc. I think we can land the consumer-group split before the freeze if we start the shadow read this week. One worry: rebalancing during a spike is exactly when we can least afford it.',
      'Makes sense. I will start the shadow read tomorrow and keep it behind the flag until we have a full day of clean diffs. Rebalancing during a spike is the right thing to be nervous about — I will write down what we do if it happens mid-incident before we flip anything.'],
    ['Dev Okonjo', 'PR #2841 ready for another look',
      'Addressed the retry-budget comments. Budget is per-org now, floor of 10, ratio 0.2. Added a test for the exhausted case. Nothing else changed.',
      'Looked it over, this reads well now. One small thing: the floor of 10 is doing a lot of work and nothing explains why. A one-line comment is enough. Otherwise ship it.'],
    ['Ines Halvorsen', 'Design review Thursday?',
      'I have the empty states and the chart legend contrast fix ready. Thirty minutes should cover it. Thursday 2pm or Friday morning both work for me.',
      'Thursday 2pm works. I will bring the funnel empty state too, since it has the same problem and we may as well fix them together.'],
    ['Tomas Reyes', 'Weekly digest is an hour off in Europe',
      'Two customers wrote in. Both in Lisbon. Both got the digest at 8am instead of 9. Smells like we are formatting in UTC and then localizing the label only.',
      'You are right, we format in UTC and then localize the label only. The fix is small. I will add a test with a Lisbon timezone so this cannot come back quietly.'],
    ['Priya Nandi', 'Numbers for the Q4 doc',
      'Ingest lag p99 is down to 840ms from 2.1s. Export endpoint timeouts are basically gone since the per-org limit. I put the queries in the appendix so nobody has to trust me.',
      'This is exactly what I needed, thank you. I am going to quote the p99 line and link the appendix rather than paste the numbers, so the doc stays true when the numbers move.'],
    ['Kwame Asare', 'Incident review notes',
      'Short version: the sink got slow, every worker retried on the same tick, and we made it worse. Action item is jitter, which is already merged. Writing it up properly today.',
      'That matches what I saw in the traces. When you write it up, can you include the ten minutes before the alert fired? The interesting part is that nothing paged while the queue was already backing up.'],
    ['Halcyon Status', 'Scheduled maintenance — Sunday 02:00 UTC',
      'Read replicas will fail over one at a time. Expected impact: a few seconds of elevated query latency per replica. No ingest downtime planned.',
      'Noted. I will silence the replica lag alert for that window so nobody gets paged for the planned failover, and re-enable it Monday morning.'],
    ['Mara Velez', 'Re: 1:1 tomorrow',
      'Can we push to 3? I have the customer call running long. Nothing urgent, I just want to talk through where the rewrite ends and the next thing starts.',
      'Three is fine. I will come with a rough line for where I think the rewrite ends — mainly the consumer-group split landing and the lag dashboard being something we trust.'],
    ['Lena Fischer', 'Dashboard route is slow on cold load',
      'First paint is around 1.6s on a cold cache. Most of it is the tile reflow running twice. I can take it if nobody else has started.',
      'Please do take it. The double reflow is on us — the tile grid measures before the fonts settle. If you want a second pair of eyes on the fix I am around most of tomorrow.'],
    ['Rui Barbosa', 'Flag evaluation on cold starts',
      'Flag evaluation is adding about 40ms to cold starts because we read through to the KV store before the cache warms. Options: prefetch on boot, or accept defaults for the first request.',
      'Prefetch on boot, I think. Accepting defaults for the first request means the first user of every cold instance sees different behaviour, and that is the kind of bug we would never reproduce.'],
    ['Ines Halvorsen', 'Contrast pass on the chart legend',
      'The legend fails contrast in dark mode at small sizes. I have new tokens that pass at 4.5:1 without changing the palette much. Screenshots in the Figma file.',
      'These look good and close enough to the old palette that nobody will file a bug about the change. Ship it — and if the tokens are reusable, let us put them in the shared file rather than the page.'],
    ['Dev Okonjo', 'Consumer group split — rollout plan',
      'Draft plan: shadow read for a day, then move ten percent of partitions, then the rest. Rollback is flipping the flag, but in-flight batches would be dropped on rebalance.',
      'The plan is right, the rollback is the weak part. Dropping in-flight batches on rollback means we lose data exactly when something is already wrong. Can we drain before rebalancing, even if it makes rollback slower?'],
    ['Priya Nandi', 'Retention chart looks wrong at month boundaries',
      'Week 4 retention jumps every time a month ends. I think we bucket by calendar week in one query and rolling week in the other.',
      'Good find. Calendar week in one place and rolling week in the other would produce exactly that jump. I will make both rolling and add a test at a month boundary so it stays that way.'],
    ['Tomas Reyes', 'CSV export truncating quietly',
      'A customer exported 40k rows and got 10k with no warning. They only noticed a week later. Can we at least tell them, even if we keep the limit?',
      'Silently dropping data is the worst version of this, agreed. Short term I will add the warning and the row count to the export. Longer term the limit should be a paged export rather than a cliff.'],
  ],

  /* ---------------- Figma ---------------- */
  figmaLayers: [
    'Dashboard / Overview', 'Card — Ingest lag', 'Card — Events / min', 'Chart legend',
    'Empty state / No events', 'Toolbar', 'Filter pill', 'Sidebar / Nav', 'Toast — Sampling on',
    'Button / Primary', 'Table / Row', 'Badge / Live',
  ],
  figmaFrames: ['Overview', 'Empty state', 'Funnel', 'Settings'],

  /* ---------------- PostHog ---------------- */
  metrics: [
    ['Events / min', 12400, 'up'], ['Ingest lag p99', 840, 'down'],
    ['Active orgs', 318, 'up'], ['Failed writes', 12, 'down'],
  ],
  phInsights: [
    'Signup → first event', 'Weekly active orgs', 'Dashboard load p95',
    'Export endpoint errors', 'Retention — week 4', 'Funnel: onboarding',
    'SDK installs by language', 'Flag evaluations / min', 'Replay minutes stored',
    'Query cost by org', 'Webhook delivery rate', 'Cold start p95',
  ],

  /* ---------------- notifications ---------------- */
  notifs: [
    ['linear', 'Linear', '{p} moved ENG-412 to In Review'],
    ['linear', 'Linear', '{p} mentioned you in ENG-388'],
    ['linear', 'Linear', '{p} assigned PLAT-207 to you'],
    ['gmail', 'Gmail', '{p} — Design review Thursday?'],
    ['gmail', 'Gmail', '{p} — Flag evaluation on cold starts'],
    ['vscode', 'GitHub Actions', 'Build passed on {branch}'],
    ['vscode', 'GitHub', '{p} approved your pull request'],
    ['figma', 'Figma', '{p} is editing Dashboard / Overview'],
    ['figma', 'Figma', 'New comment on Empty state / No events'],
    ['posthog', 'PostHog', 'Ingest lag p99 is back under 1s'],
    ['posthog', 'PostHog', 'Alert resolved: failed writes below threshold'],
    ['roam', 'Roam', '{p} knocked on your office'],
    ['roam', 'Roam', 'Standup starts in the Theater in 2 minutes'],
    ['roam', 'Roam', '{p} is screensharing in the Ingest war room'],
    ['gmail', 'Calendar', 'Standup in 10 minutes — Meet link'],
  ],
};
